endpoints:
  - name: wesite                 # Name of your endpoint, can be anything
    url: "https://twin.sh/health"
    interval: 30s                  # Duration to wait between every status check (default: 60s)
    conditions:
      - "[STATUS] == 200"         # Status must be 200
      - "[BODY].status == UP"     # The json path "$.status" must be equal to UP
      - "[RESPONSE_TIME] < 300"   # Response time must be under 300ms

  - name: back-end
    group: core
    url: "https://example.org/"
    interval: 30s
    conditions:
      - "[STATUS] == 200"
      - "[CERTIFICATE_EXPIRATION] > 48h"

  - name: monitoring
    group: internal
    url: "https://example.org/"
    interval: 30s
    conditions:
      - "[STATUS] == 200"

  - name: LRT
    group: internal
    url: "https://lrt.lt/"
    interval: 30s
    conditions:
      - "[STATUS] == 200"

  - name: example-dns-query
    url: "8.8.8.8" # Address of the DNS server to use
    interval: 30s
    dns:
      query-name: "example.com"
      query-type: "A"
    conditions:
      - "[BODY] == 93.184.215.14"
      - "[DNS_RCODE] == NOERROR"

  - name: icmp-ping
    url: "icmp://example.org"
    interval: 30s
    conditions:
      - "[CONNECTED] == true"

  - name: check-domain-expiration
    url: "https://example.org/"
    interval: 30s
    conditions:
      - "[DOMAIN_EXPIRATION] > 720h"
 