- name: Pull Docker Image
  hosts: all
  become: true
  tasks:
    - name: Ensure Docker is installed
      apt:
        name: docker.io
        state: present

    - name: Start Docker service
      service:
        name: docker
        state: started
        enabled: true

    - name: Pull the Gatus Docker image
      command: docker pull twinproduction/gatus
      register: pull_result

    - name: Display pull result
      debug:
        var: pull_result.stdout