- name: Pull Docker Image
  hosts: all
  become: true
  tasks:
    # - name: Ensure Docker is installed
    #   apt:
    #     name: docker.io
    #     state: present

    - name: Create a directory
      ansible.builtin.file:
        path: /home/ubuntu/config
        state: directory
        mode: '0755'
        owner: ubuntu
        group: docker

    - name: Copy file with new permissions
      ansible.builtin.copy:
        src: ConfigGatus.yaml
        dest: /home/ubuntu/config/config.yaml
        mode: '0644'
        owner: ubuntu
        group: docker
        remote_src: yes


    - name: Start Docker service
      service:
        name: docker
        state: started
        enabled: true

    - name: Pull the Gatus Docker image
      command: docker pull twinproduction/gatus
      register: pull_result

    # Stop and remove existing Gatus container (if any)
    - name: Remove existing Gatus container (if running)
      docker_container:
        name: gatus
        state: absent

    # Run Gatus container
    - name: Start Gatus Docker container
      docker_container:
        name: gatus
        image: twinproduction/gatus:latest
        state: started
        ports:
          - "8080:8080"  # Map host port 8080 to container port 8080
        mounts:
          - type: bind
            source: /home/ubuntu/config/config.yaml
            target: /config/config.yaml
        env:
          GATUS_IP: "0.0.0.0"  # Optional: Set Gatus IP (adjust as needed)
        restart_policy: always
        restart: true

    - name: Display pull result
      debug:
        var: pull_result.stdout
