name: Setup Docker on the VM with Ansible

on:
    workflow_dispatch:
        inputs:
            environment:
                type: choice
                description: Butaforinis pasirinkimas
                options:
                    - dev
                default: dev
jobs:

    install-docker:
        runs-on: ubuntu-latest
        defaults:
            run:
              working-directory: ./ansible
        steps:
        #Checkout code so that the palybook is accessible
            - name: Checkout code
              uses: actions/checkout@v3

            - name: Install Ansible
              run: sudo apt-get update && sudo apt-get install -y ansible

            - name: Setup SSH key for connection to AWS VM
              run: |
                mkdir -p ~/.ssh
                echo "${{secrets.AWS_SSH_KEY}}" > ~/.ssh/id_rsa
                chmod 600 ~/.ssh/id_rsa

            - name: Run ansible playbook to install Docker
              run: ansible-playbook -u ubuntu -i 3.76.114.159, --private-key ~/.ssh/id_rsa install_docker.yml
