name: Setup Gatus on the VM with Ansible

on:
    #workflow_dispatch:
    #    inputs:
    #        environment:
    #            type: choice
    #            description: Butaforinis pasirinkimas 2
    #            options:
    #                - dev
    #            default: dev

    workflow_run:
      workflows:
        - Setup Docker on the VM with Ansible
      types:
        - completed

jobs:

    install-docker:
        runs-on: ubuntu-latest
        defaults:
            run:
              working-directory: ./ansible
        steps:
        #Checkout code so that the palybook is accessible
            - name: Checkout code
              uses: actions/checkout@v3

            - name: Create SSH directory
              run: mkdir -p ~/.ssh

            - name: Add host to known_hosts
              run: ssh-keyscan -H 3.76.114.159 >> ~/.ssh/known_hosts

            - name: Check and Install Ansible
              run: |
                if ! command -v ansible &> /dev/null; then
                  echo "Ansible not found. Installing..."
                  sudo apt-get update && sudo apt-get install -y ansible
                else
                  echo "Ansible is already installed."
                fi
                
            - name: Ensure everything is up to date
              run: |
                sudo dpkg --configure -a
                sudo apt-get update --fix-missing
                sudo apt-get -f install 


            - name: Setup SSH key for connection to AWS VM
              run: |
                mkdir -p ~/.ssh
                echo "${{secrets.AWS_SSH_KEY}}" > ~/.ssh/id_rsa
                chmod 600 ~/.ssh/id_rsa

            - name: Run Gatus playbook to install Gatus
              run: ansible-playbook -u ubuntu -i 3.76.114.159, --private-key ~/.ssh/id_rsa install_gatus.yml
